# Generated by Django 4.0.6 on 2022-08-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_survey_surveycategory_usersurvey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iin',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parol',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_till',
            field=models.DateTimeField(max_length=300, null=True),
        ),
    ]
